name: Run Cypress Tests using Multiple Machines

on: push

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false

  firefox:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: '92.0.1'

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run ff
          tag: firefox
          record: ${{ job.status == 'success' && matrix.container == '1' }}
