name: Run Cypress Tests using on Single Machine

on: push

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [firefox, webkit]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up ${{ matrix.browser }}
        uses: browser-actions/setup-firefox@v1
        if: matrix.browser == 'firefox'
        with:
          firefox-version: '92.0.1'

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browser }}
          command: npm run ${{ matrix.browser }}
          tag: ${{ matrix.browser }}
