name: Run Cypress Tests using on Single Machine
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: '92'

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: firefox
          command: npm run ff
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
