name: Run Cypress Tests using on Single Machine

on: push

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browser }}
          command: npm run ${{ matrix.browser }}

  firefox:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [firefox]

    steps:
      - name: Cypress run - Firefox
        uses: cypress-io/github-action@v5
        with:
          browser: firefox
          command: npm run firefox

  chrome:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome]

    steps:
      - name: Cypress run - Chrome
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          command: npm run chrome

  webkit:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [webkit]

    steps:
      - name: Cypress run - WebKit
        uses: cypress-io/github-action@v5
        with:
          browser: webkit
          command: npm run webkit
