name: Cypress Tests

on: push

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEBUG: "cypress:*"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false

  electron-browser:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    strategy:
      # run 3 copies of the current job in parallel
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Testing in Electron"
        uses: cypress-io/github-action@v5
        with:
          build: npx cypress info
          record: true
          parallel: true
          group: "Electron"

  chrome-browser:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    strategy:
      # run 3 copies of the current job in parallel
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Testing in Chrome"
        uses: cypress-io/github-action@v5
        with:
          build: npx cypress info
          browser: chrome
          record: true
          parallel: true
          group: "Chrome"

  firefox-browser:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    strategy:
      # run 3 copies of the current job in parallel
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Testing in Firefox"
        uses: cypress-io/github-action@v5
        with:
          build: npx cypress info
          browser: firefox
          record: true
          parallel: true
          group: "Firefox"

  edge-browser:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    strategy:
      # run 3 copies of the current job in parallel
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Testing in Edge"
        uses: cypress-io/github-action@v5
        with:
          build: npx cypress info
          browser: edge
          record: true
          parallel: true
          group: "Edge"
          config: "video=true"

  webkit-browser:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    strategy:
      # run 3 copies of the current job in parallel
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Playwright dependencies for WebKit
        run: npx playwright install-deps webkit

      - name: "Testing in WebKit"
        uses: cypress-io/github-action@v5
        with:
          build: npx cypress info
          browser: webkit
          record: true
          parallel: true
          group: "WebKit"
          config: "video=true,experimentalWebKitSupport=true"
